const CATEGORY_RULES: Array<{ category: string; keywords: string[] }> = [
  {
    category: 'Produce',
    keywords: [
      'apple',
      'banana',
      'lettuce',
      'spinach',
      'tomato',
      'onion',
      'garlic',
      'pepper',
      'carrot',
      'potato',
      'broccoli',
      'mushroom',
      'celery',
      'cucumber',
      'zucchini',
      'lemon',
      'lime',
      'avocado',
      'corn',
      'pea',
      'bean',
      'squash',
      'kale',
      'cilantro',
      'parsley',
      'basil',
      'ginger',
      'scallion',
      'shallot',
      'leek',
      'asparagus',
      'artichoke',
      'eggplant',
      'fennel',
      'radish',
      'beet',
      'berry',
      'grape',
      'mango',
      'peach',
      'pear',
      'plum',
      'orange',
      'strawberry',
      'blueberry',
      'raspberry',
      'watermelon',
      'melon',
      'cabbage',
      'arugula',
      'chard',
      'collard',
      'turnip',
      'sweet potato',
      'yam',
    ],
  },
  {
    category: 'Dairy',
    keywords: [
      'milk',
      'cream',
      'butter',
      'cheese',
      'yogurt',
      'sour cream',
      'egg',
      'parmesan',
      'mozzarella',
      'cheddar',
      'ricotta',
      'brie',
      'feta',
      'gouda',
      'gruyere',
      'provolone',
      'swiss',
      'cream cheese',
      'half and half',
      'whipping cream',
      'heavy cream',
    ],
  },
  {
    category: 'Meat',
    keywords: [
      'chicken',
      'beef',
      'pork',
      'lamb',
      'turkey',
      'bacon',
      'sausage',
      'ham',
      'steak',
      'ground beef',
      'ground turkey',
      'ground pork',
      'brisket',
      'rib',
      'loin',
      'tenderloin',
      'thigh',
      'breast',
      'drumstick',
      'wing',
      'duck',
      'veal',
      'bison',
      'venison',
      'prosciutto',
      'pancetta',
      'salami',
      'pepperoni',
      'chorizo',
    ],
  },
  {
    category: 'Seafood',
    keywords: [
      'fish',
      'salmon',
      'tuna',
      'shrimp',
      'crab',
      'lobster',
      'scallop',
      'clam',
      'oyster',
      'cod',
      'tilapia',
      'halibut',
      'mahi',
      'sardine',
      'anchovy',
      'squid',
      'octopus',
      'mussel',
      'sea bass',
      'trout',
      'snapper',
    ],
  },
  {
    category: 'Bakery',
    keywords: [
      'bread',
      'flour',
      'yeast',
      'bun',
      'roll',
      'bagel',
      'croissant',
      'pita',
      'tortilla',
      'naan',
      'baguette',
      'sourdough',
      'breadcrumb',
      'panko',
      'cracker',
      'pretzel',
    ],
  },
  { category: 'Frozen', keywords: ['frozen'] },
  {
    category: 'Beverages',
    keywords: [
      'juice',
      'wine',
      'beer',
      'coffee',
      'tea',
      'soda',
      'coconut milk',
      'almond milk',
      'oat milk',
      'broth',
      'stock',
    ],
  },
  {
    category: 'Household',
    keywords: [
      'foil',
      'plastic wrap',
      'parchment',
      'paper bag',
      'paper towel',
      'soap',
      'detergent',
      'sponge',
      'zip',
      'storage bag',
    ],
  },
  {
    category: 'Pantry Staples',
    keywords: [
      'oil',
      'vinegar',
      'salt',
      'sugar',
      'honey',
      'soy sauce',
      'sauce',
      'paste',
      'rice',
      'pasta',
      'noodle',
      'oat',
      'cereal',
      'canned',
      'dried',
      'spice',
      'herb',
      'cumin',
      'paprika',
      'oregano',
      'thyme',
      'bay leaf',
      'cinnamon',
      'nutmeg',
      'clove',
      'turmeric',
      'curry',
      'chili powder',
      'cayenne',
      'mustard',
      'ketchup',
      'mayo',
      'ranch',
      'dressing',
      'syrup',
      'jam',
      'jelly',
      'peanut butter',
      'almond butter',
      'chocolate',
      'cocoa',
      'vanilla',
      'baking powder',
      'baking soda',
      'cornstarch',
      'lentil',
      'chickpea',
      'tofu',
      'tempeh',
      'quinoa',
      'couscous',
      'barley',
      'granola',
      'nut',
      'almond',
      'walnut',
      'pecan',
      'cashew',
      'pistachio',
      'seed',
      'sesame',
      'flaxseed',
      'sunflower',
      'raisin',
      'dried fruit',
    ],
  },
];

/**
 * Infer an ingredient category from its name using keyword rules.
 * Returns the first matching category, or 'Other' if no rule matches.
 */
export function inferCategory(name: string): string {
  const lower = name.toLowerCase();
  for (const rule of CATEGORY_RULES) {
    if (rule.keywords.some((kw) => lower.includes(kw))) {
      return rule.category;
    }
  }
  return 'Other';
}
